<?php

namespace App\Http\Controllers\Dashboards;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AgentsController extends Controller
{
    public function agents()
    {
        $data = [
            'totalAgents' => 336,
            'improductive' => 13.3,
            'improductiveSummary' => [
                [
                    'agent' => 'Ana',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Wjlangsovo',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'SmartNav',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Stc Electric',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Viting',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Scaffolding',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Scsi',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Ballygroup',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Tellarcom',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Wcumberium',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'The Avon Lounge',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Skyguard',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Wyrprite',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Graco Asia',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Ennoot',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Judton',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Mcdastabri',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Lynn Real Estate',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Thinovosts',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Jamark',
                    'percent' => random_int(1, 99),
                ],
            ],
            'productiveSummary' => [
                [
                    'agent' => 'Ana',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Wjlangsovo',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'SmartNav',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Stc Electric',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Viting',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Scaffolding',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Scsi',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Ballygroup',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Tellarcom',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Wcumberium',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'The Avon Lounge',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Skyguard',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Wyrprite',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Graco Asia',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Ennoot',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Judton',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Mcdastabri',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Lynn Real Estate',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Thinovosts',
                    'percent' => random_int(1, 99),
                ],
                [
                    'agent' => 'Jamark',
                    'percent' => random_int(1, 99),
                ],
            ],
            'heatMap' => [
                'agents' => [
                    'Wjlangsovo',
                    'SmartNav',
                    'Stc Electric',
                    'Viting',
                    'Scaffolding',
                    'Scsi',
                    'Ballygroup',
                    'Tellarcom',
                    'Wcumberium',
                    'The Avon Lounge',
                    'Skyguard',
                    'Wyrprite',
                    'Graco Asia',
                    'Ennoot',
                    'Judton',
                    'Mcdastabri',
                    'Lynn Real Estate',
                    'Thinovosts',
                    'Jamark',
                ],
                'occurrences' => [
                    'Third-party scheduling',
                    'Message',
                    'Future contact/Broken call',
                    'Payment promise',
                    'Mute call',
                    'Incorrect phone',
                    'Answering machine/Machine voice',
                    'Client scheduling',
                    'Does not confirm data',
                    'Claims payment',
                    'System problems',
                    'Refuse payment',
                    'Unemployment/Disease/Decease',
                    'Operation transfer',
                ],
                'data' => [
                    'Wjlangsovo' => [
                        'Third-party scheduling' => random_int(0, 300),
                        'Message' => random_int(0, 300),
                        'Future contact/Broken call' => random_int(0, 300),
                        'Payment promise' => random_int(0, 300),
                        'Mute call' => random_int(0, 300),
                        'Incorrect phone' => random_int(0, 300),
                        'Answering machine/Machine voice' => random_int(0, 300),
                        'Client scheduling' => random_int(0, 300),
                        'Does not confirm data' => random_int(0, 300),
                        'Claims payment' => random_int(0, 300),
                        'System problems' => random_int(0, 300),
                        'Refuse payment' => random_int(0, 300),
                        'Unemployment/Disease/Decease' => random_int(0, 300),
                        'Operation transfer' => random_int(0, 300),
                    ],
                    'SmartNav' => [
                        'Third-party scheduling' => random_int(0, 300),
                        'Message' => random_int(0, 300),
                        'Future contact/Broken call' => random_int(0, 300),
                        'Payment promise' => random_int(0, 300),
                        'Mute call' => random_int(0, 300),
                        'Incorrect phone' => random_int(0, 300),
                        'Answering machine/Machine voice' => random_int(0, 300),
                        'Client scheduling' => random_int(0, 300),
                        'Does not confirm data' => random_int(0, 300),
                        'Claims payment' => random_int(0, 300),
                        'System problems' => random_int(0, 300),
                        'Refuse payment' => random_int(0, 300),
                        'Unemployment/Disease/Decease' => random_int(0, 300),
                        'Operation transfer' => random_int(0, 300),
                    ],
                    'Stc Electric' => [
                        'Third-party scheduling' => random_int(0, 300),
                        'Message' => random_int(0, 300),
                        'Future contact/Broken call' => random_int(0, 300),
                        'Payment promise' => random_int(0, 300),
                        'Mute call' => random_int(0, 300),
                        'Incorrect phone' => random_int(0, 300),
                        'Answering machine/Machine voice' => random_int(0, 300),
                        'Client scheduling' => random_int(0, 300),
                        'Does not confirm data' => random_int(0, 300),
                        'Claims payment' => random_int(0, 300),
                        'System problems' => random_int(0, 300),
                        'Refuse payment' => random_int(0, 300),
                        'Unemployment/Disease/Decease' => random_int(0, 300),
                        'Operation transfer' => random_int(0, 300),
                    ],
                    'Viting' => [
                        'Third-party scheduling' => random_int(0, 300),
                        'Message' => random_int(0, 300),
                        'Future contact/Broken call' => random_int(0, 300),
                        'Payment promise' => random_int(0, 300),
                        'Mute call' => random_int(0, 300),
                        'Incorrect phone' => random_int(0, 300),
                        'Answering machine/Machine voice' => random_int(0, 300),
                        'Client scheduling' => random_int(0, 300),
                        'Does not confirm data' => random_int(0, 300),
                        'Claims payment' => random_int(0, 300),
                        'System problems' => random_int(0, 300),
                        'Refuse payment' => random_int(0, 300),
                        'Unemployment/Disease/Decease' => random_int(0, 300),
                        'Operation transfer' => random_int(0, 300),
                    ],
                    'Scaffolding' => [
                        'Third-party scheduling' => random_int(0, 300),
                        'Message' => random_int(0, 300),
                        'Future contact/Broken call' => random_int(0, 300),
                        'Payment promise' => random_int(0, 300),
                        'Mute call' => random_int(0, 300),
                        'Incorrect phone' => random_int(0, 300),
                        'Answering machine/Machine voice' => random_int(0, 300),
                        'Client scheduling' => random_int(0, 300),
                        'Does not confirm data' => random_int(0, 300),
                        'Claims payment' => random_int(0, 300),
                        'System problems' => random_int(0, 300),
                        'Refuse payment' => random_int(0, 300),
                        'Unemployment/Disease/Decease' => random_int(0, 300),
                        'Operation transfer' => random_int(0, 300),
                    ],
                    'Scsi' => [
                        'Third-party scheduling' => random_int(0, 300),
                        'Message' => random_int(0, 300),
                        'Future contact/Broken call' => random_int(0, 300),
                        'Payment promise' => random_int(0, 300),
                        'Mute call' => random_int(0, 300),
                        'Incorrect phone' => random_int(0, 300),
                        'Answering machine/Machine voice' => random_int(0, 300),
                        'Client scheduling' => random_int(0, 300),
                        'Does not confirm data' => random_int(0, 300),
                        'Claims payment' => random_int(0, 300),
                        'System problems' => random_int(0, 300),
                        'Refuse payment' => random_int(0, 300),
                        'Unemployment/Disease/Decease' => random_int(0, 300),
                        'Operation transfer' => random_int(0, 300),
                    ],
                    'Ballygroup' => [
                        'Third-party scheduling' => random_int(0, 300),
                        'Message' => random_int(0, 300),
                        'Future contact/Broken call' => random_int(0, 300),
                        'Payment promise' => random_int(0, 300),
                        'Mute call' => random_int(0, 300),
                        'Incorrect phone' => random_int(0, 300),
                        'Answering machine/Machine voice' => random_int(0, 300),
                        'Client scheduling' => random_int(0, 300),
                        'Does not confirm data' => random_int(0, 300),
                        'Claims payment' => random_int(0, 300),
                        'System problems' => random_int(0, 300),
                        'Refuse payment' => random_int(0, 300),
                        'Unemployment/Disease/Decease' => random_int(0, 300),
                        'Operation transfer' => random_int(0, 300),
                    ],
                    'Tellarcom' => [
                        'Third-party scheduling' => random_int(0, 300),
                        'Message' => random_int(0, 300),
                        'Future contact/Broken call' => random_int(0, 300),
                        'Payment promise' => random_int(0, 300),
                        'Mute call' => random_int(0, 300),
                        'Incorrect phone' => random_int(0, 300),
                        'Answering machine/Machine voice' => random_int(0, 300),
                        'Client scheduling' => random_int(0, 300),
                        'Does not confirm data' => random_int(0, 300),
                        'Claims payment' => random_int(0, 300),
                        'System problems' => random_int(0, 300),
                        'Refuse payment' => random_int(0, 300),
                        'Unemployment/Disease/Decease' => random_int(0, 300),
                        'Operation transfer' => random_int(0, 300),
                    ],
                    'Wcumberium' => [
                        'Third-party scheduling' => random_int(0, 300),
                        'Message' => random_int(0, 300),
                        'Future contact/Broken call' => random_int(0, 300),
                        'Payment promise' => random_int(0, 300),
                        'Mute call' => random_int(0, 300),
                        'Incorrect phone' => random_int(0, 300),
                        'Answering machine/Machine voice' => random_int(0, 300),
                        'Client scheduling' => random_int(0, 300),
                        'Does not confirm data' => random_int(0, 300),
                        'Claims payment' => random_int(0, 300),
                        'System problems' => random_int(0, 300),
                        'Refuse payment' => random_int(0, 300),
                        'Unemployment/Disease/Decease' => random_int(0, 300),
                        'Operation transfer' => random_int(0, 300),
                    ],
                    'The Avon Lounge' => [
                        'Third-party scheduling' => random_int(0, 300),
                        'Message' => random_int(0, 300),
                        'Future contact/Broken call' => random_int(0, 300),
                        'Payment promise' => random_int(0, 300),
                        'Mute call' => random_int(0, 300),
                        'Incorrect phone' => random_int(0, 300),
                        'Answering machine/Machine voice' => random_int(0, 300),
                        'Client scheduling' => random_int(0, 300),
                        'Does not confirm data' => random_int(0, 300),
                        'Claims payment' => random_int(0, 300),
                        'System problems' => random_int(0, 300),
                        'Refuse payment' => random_int(0, 300),
                        'Unemployment/Disease/Decease' => random_int(0, 300),
                        'Operation transfer' => random_int(0, 300),
                    ],
                    'Skyguard' => [
                        'Third-party scheduling' => random_int(0, 300),
                        'Message' => random_int(0, 300),
                        'Future contact/Broken call' => random_int(0, 300),
                        'Payment promise' => random_int(0, 300),
                        'Mute call' => random_int(0, 300),
                        'Incorrect phone' => random_int(0, 300),
                        'Answering machine/Machine voice' => random_int(0, 300),
                        'Client scheduling' => random_int(0, 300),
                        'Does not confirm data' => random_int(0, 300),
                        'Claims payment' => random_int(0, 300),
                        'System problems' => random_int(0, 300),
                        'Refuse payment' => random_int(0, 300),
                        'Unemployment/Disease/Decease' => random_int(0, 300),
                        'Operation transfer' => random_int(0, 300),
                    ],
                    'Wyrprite' => [
                        'Third-party scheduling' => random_int(0, 300),
                        'Message' => random_int(0, 300),
                        'Future contact/Broken call' => random_int(0, 300),
                        'Payment promise' => random_int(0, 300),
                        'Mute call' => random_int(0, 300),
                        'Incorrect phone' => random_int(0, 300),
                        'Answering machine/Machine voice' => random_int(0, 300),
                        'Client scheduling' => random_int(0, 300),
                        'Does not confirm data' => random_int(0, 300),
                        'Claims payment' => random_int(0, 300),
                        'System problems' => random_int(0, 300),
                        'Refuse payment' => random_int(0, 300),
                        'Unemployment/Disease/Decease' => random_int(0, 300),
                        'Operation transfer' => random_int(0, 300),
                    ],
                    'Graco Asia' => [
                        'Third-party scheduling' => random_int(0, 300),
                        'Message' => random_int(0, 300),
                        'Future contact/Broken call' => random_int(0, 300),
                        'Payment promise' => random_int(0, 300),
                        'Mute call' => random_int(0, 300),
                        'Incorrect phone' => random_int(0, 300),
                        'Answering machine/Machine voice' => random_int(0, 300),
                        'Client scheduling' => random_int(0, 300),
                        'Does not confirm data' => random_int(0, 300),
                        'Claims payment' => random_int(0, 300),
                        'System problems' => random_int(0, 300),
                        'Refuse payment' => random_int(0, 300),
                        'Unemployment/Disease/Decease' => random_int(0, 300),
                        'Operation transfer' => random_int(0, 300),
                    ],
                    'Ennoot' => [
                        'Third-party scheduling' => random_int(0, 300),
                        'Message' => random_int(0, 300),
                        'Future contact/Broken call' => random_int(0, 300),
                        'Payment promise' => random_int(0, 300),
                        'Mute call' => random_int(0, 300),
                        'Incorrect phone' => random_int(0, 300),
                        'Answering machine/Machine voice' => random_int(0, 300),
                        'Client scheduling' => random_int(0, 300),
                        'Does not confirm data' => random_int(0, 300),
                        'Claims payment' => random_int(0, 300),
                        'System problems' => random_int(0, 300),
                        'Refuse payment' => random_int(0, 300),
                        'Unemployment/Disease/Decease' => random_int(0, 300),
                        'Operation transfer' => random_int(0, 300),
                    ],
                    'Judton' => [
                        'Third-party scheduling' => random_int(0, 300),
                        'Message' => random_int(0, 300),
                        'Future contact/Broken call' => random_int(0, 300),
                        'Payment promise' => random_int(0, 300),
                        'Mute call' => random_int(0, 300),
                        'Incorrect phone' => random_int(0, 300),
                        'Answering machine/Machine voice' => random_int(0, 300),
                        'Client scheduling' => random_int(0, 300),
                        'Does not confirm data' => random_int(0, 300),
                        'Claims payment' => random_int(0, 300),
                        'System problems' => random_int(0, 300),
                        'Refuse payment' => random_int(0, 300),
                        'Unemployment/Disease/Decease' => random_int(0, 300),
                        'Operation transfer' => random_int(0, 300),
                    ],
                    'Mcdastabri' => [
                        'Third-party scheduling' => random_int(0, 300),
                        'Message' => random_int(0, 300),
                        'Future contact/Broken call' => random_int(0, 300),
                        'Payment promise' => random_int(0, 300),
                        'Mute call' => random_int(0, 300),
                        'Incorrect phone' => random_int(0, 300),
                        'Answering machine/Machine voice' => random_int(0, 300),
                        'Client scheduling' => random_int(0, 300),
                        'Does not confirm data' => random_int(0, 300),
                        'Claims payment' => random_int(0, 300),
                        'System problems' => random_int(0, 300),
                        'Refuse payment' => random_int(0, 300),
                        'Unemployment/Disease/Decease' => random_int(0, 300),
                        'Operation transfer' => random_int(0, 300),
                    ],
                    'Lynn Real Estate' => [
                        'Third-party scheduling' => random_int(0, 300),
                        'Message' => random_int(0, 300),
                        'Future contact/Broken call' => random_int(0, 300),
                        'Payment promise' => random_int(0, 300),
                        'Mute call' => random_int(0, 300),
                        'Incorrect phone' => random_int(0, 300),
                        'Answering machine/Machine voice' => random_int(0, 300),
                        'Client scheduling' => random_int(0, 300),
                        'Does not confirm data' => random_int(0, 300),
                        'Claims payment' => random_int(0, 300),
                        'System problems' => random_int(0, 300),
                        'Refuse payment' => random_int(0, 300),
                        'Unemployment/Disease/Decease' => random_int(0, 300),
                        'Operation transfer' => random_int(0, 300),
                    ],
                    'Thinovosts' => [
                        'Third-party scheduling' => random_int(0, 300),
                        'Message' => random_int(0, 300),
                        'Future contact/Broken call' => random_int(0, 300),
                        'Payment promise' => random_int(0, 300),
                        'Mute call' => random_int(0, 300),
                        'Incorrect phone' => random_int(0, 300),
                        'Answering machine/Machine voice' => random_int(0, 300),
                        'Client scheduling' => random_int(0, 300),
                        'Does not confirm data' => random_int(0, 300),
                        'Claims payment' => random_int(0, 300),
                        'System problems' => random_int(0, 300),
                        'Refuse payment' => random_int(0, 300),
                        'Unemployment/Disease/Decease' => random_int(0, 300),
                        'Operation transfer' => random_int(0, 300),
                    ],
                    'Jamark' => [
                        'Third-party scheduling' => random_int(0, 300),
                        'Message' => random_int(0, 300),
                        'Future contact/Broken call' => random_int(0, 300),
                        'Payment promise' => random_int(0, 300),
                        'Mute call' => random_int(0, 300),
                        'Incorrect phone' => random_int(0, 300),
                        'Answering machine/Machine voice' => random_int(0, 300),
                        'Client scheduling' => random_int(0, 300),
                        'Does not confirm data' => random_int(0, 300),
                        'Claims payment' => random_int(0, 300),
                        'System problems' => random_int(0, 300),
                        'Refuse payment' => random_int(0, 300),
                        'Unemployment/Disease/Decease' => random_int(0, 300),
                        'Operation transfer' => random_int(0, 300),
                    ],
                ]
            ],
            'distributionByAgents' => [
                'indicators' => [
                    'Agent',
                    'Attempts',
                    'Answered',
                    'CPC',
                    '%CPC',
                    'CPCA',
                    '%CPCA',
                    'Deals',
                    '%Deals',
                ],
                'data' => [
                    [
                        'Agent' => random_int(1000, 9999),
                        'Attempts' => random_int(100, 999),
                        'Answered' => random_int(100, 999),
                        'CPC' => random_int(100, 999),
                        '%CPC' => random_int(1, 99),
                        'CPCA' => random_int(100, 999),
                        '%CPCA' => random_int(1, 99),
                        'Deals' => random_int(100, 999),
                        '%Deals' => random_int(1, 99),
                    ],
                    [
                        'Agent' => random_int(1000, 9999),
                        'Attempts' => random_int(100, 999),
                        'Answered' => random_int(100, 999),
                        'CPC' => random_int(100, 999),
                        '%CPC' => random_int(1, 99),
                        'CPCA' => random_int(100, 999),
                        '%CPCA' => random_int(1, 99),
                        'Deals' => random_int(100, 999),
                        '%Deals' => random_int(1, 99),
                    ],
                    [
                        'Agent' => random_int(1000, 9999),
                        'Attempts' => random_int(100, 999),
                        'Answered' => random_int(100, 999),
                        'CPC' => random_int(100, 999),
                        '%CPC' => random_int(1, 99),
                        'CPCA' => random_int(100, 999),
                        '%CPCA' => random_int(1, 99),
                        'Deals' => random_int(100, 999),
                        '%Deals' => random_int(1, 99),
                    ],
                    [
                        'Agent' => random_int(1000, 9999),
                        'Attempts' => random_int(100, 999),
                        'Answered' => random_int(100, 999),
                        'CPC' => random_int(100, 999),
                        '%CPC' => random_int(1, 99),
                        'CPCA' => random_int(100, 999),
                        '%CPCA' => random_int(1, 99),
                        'Deals' => random_int(100, 999),
                        '%Deals' => random_int(1, 99),
                    ],
                    [
                        'Agent' => random_int(1000, 9999),
                        'Attempts' => random_int(100, 999),
                        'Answered' => random_int(100, 999),
                        'CPC' => random_int(100, 999),
                        '%CPC' => random_int(1, 99),
                        'CPCA' => random_int(100, 999),
                        '%CPCA' => random_int(1, 99),
                        'Deals' => random_int(100, 999),
                        '%Deals' => random_int(1, 99),
                    ],
                    [
                        'Agent' => random_int(1000, 9999),
                        'Attempts' => random_int(100, 999),
                        'Answered' => random_int(100, 999),
                        'CPC' => random_int(100, 999),
                        '%CPC' => random_int(1, 99),
                        'CPCA' => random_int(100, 999),
                        '%CPCA' => random_int(1, 99),
                        'Deals' => random_int(100, 999),
                        '%Deals' => random_int(1, 99),
                    ],
                    [
                        'Agent' => random_int(1000, 9999),
                        'Attempts' => random_int(100, 999),
                        'Answered' => random_int(100, 999),
                        'CPC' => random_int(100, 999),
                        '%CPC' => random_int(1, 99),
                        'CPCA' => random_int(100, 999),
                        '%CPCA' => random_int(1, 99),
                        'Deals' => random_int(100, 999),
                        '%Deals' => random_int(1, 99),
                    ],
                    [
                        'Agent' => random_int(1000, 9999),
                        'Attempts' => random_int(100, 999),
                        'Answered' => random_int(100, 999),
                        'CPC' => random_int(100, 999),
                        '%CPC' => random_int(1, 99),
                        'CPCA' => random_int(100, 999),
                        '%CPCA' => random_int(1, 99),
                        'Deals' => random_int(100, 999),
                        '%Deals' => random_int(1, 99),
                    ],
                    [
                        'Agent' => random_int(1000, 9999),
                        'Attempts' => random_int(100, 999),
                        'Answered' => random_int(100, 999),
                        'CPC' => random_int(100, 999),
                        '%CPC' => random_int(1, 99),
                        'CPCA' => random_int(100, 999),
                        '%CPCA' => random_int(1, 99),
                        'Deals' => random_int(100, 999),
                        '%Deals' => random_int(1, 99),
                    ],
                    [
                        'Agent' => random_int(1000, 9999),
                        'Attempts' => random_int(100, 999),
                        'Answered' => random_int(100, 999),
                        'CPC' => random_int(100, 999),
                        '%CPC' => random_int(1, 99),
                        'CPCA' => random_int(100, 999),
                        '%CPCA' => random_int(1, 99),
                        'Deals' => random_int(100, 999),
                        '%Deals' => random_int(1, 99),
                    ],
                    [
                        'Agent' => random_int(1000, 9999),
                        'Attempts' => random_int(100, 999),
                        'Answered' => random_int(100, 999),
                        'CPC' => random_int(100, 999),
                        '%CPC' => random_int(1, 99),
                        'CPCA' => random_int(100, 999),
                        '%CPCA' => random_int(1, 99),
                        'Deals' => random_int(100, 999),
                        '%Deals' => random_int(1, 99),
                    ],
                    [
                        'Agent' => random_int(1000, 9999),
                        'Attempts' => random_int(100, 999),
                        'Answered' => random_int(100, 999),
                        'CPC' => random_int(100, 999),
                        '%CPC' => random_int(1, 99),
                        'CPCA' => random_int(100, 999),
                        '%CPCA' => random_int(1, 99),
                        'Deals' => random_int(100, 999),
                        '%Deals' => random_int(1, 99),
                    ],
                    [
                        'Agent' => random_int(1000, 9999),
                        'Attempts' => random_int(100, 999),
                        'Answered' => random_int(100, 999),
                        'CPC' => random_int(100, 999),
                        '%CPC' => random_int(1, 99),
                        'CPCA' => random_int(100, 999),
                        '%CPCA' => random_int(1, 99),
                        'Deals' => random_int(100, 999),
                        '%Deals' => random_int(1, 99),
                    ],
                    [
                        'Agent' => random_int(1000, 9999),
                        'Attempts' => random_int(100, 999),
                        'Answered' => random_int(100, 999),
                        'CPC' => random_int(100, 999),
                        '%CPC' => random_int(1, 99),
                        'CPCA' => random_int(100, 999),
                        '%CPCA' => random_int(1, 99),
                        'Deals' => random_int(100, 999),
                        '%Deals' => random_int(1, 99),
                    ],
                    [
                        'Agent' => random_int(1000, 9999),
                        'Attempts' => random_int(100, 999),
                        'Answered' => random_int(100, 999),
                        'CPC' => random_int(100, 999),
                        '%CPC' => random_int(1, 99),
                        'CPCA' => random_int(100, 999),
                        '%CPCA' => random_int(1, 99),
                        'Deals' => random_int(100, 999),
                        '%Deals' => random_int(1, 99),
                    ],
                    [
                        'Agent' => random_int(1000, 9999),
                        'Attempts' => random_int(100, 999),
                        'Answered' => random_int(100, 999),
                        'CPC' => random_int(100, 999),
                        '%CPC' => random_int(1, 99),
                        'CPCA' => random_int(100, 999),
                        '%CPCA' => random_int(1, 99),
                        'Deals' => random_int(100, 999),
                        '%Deals' => random_int(1, 99),
                    ],
                    [
                        'Agent' => random_int(1000, 9999),
                        'Attempts' => random_int(100, 999),
                        'Answered' => random_int(100, 999),
                        'CPC' => random_int(100, 999),
                        '%CPC' => random_int(1, 99),
                        'CPCA' => random_int(100, 999),
                        '%CPCA' => random_int(1, 99),
                        'Deals' => random_int(100, 999),
                        '%Deals' => random_int(1, 99),
                    ],
                    [
                        'Agent' => random_int(1000, 9999),
                        'Attempts' => random_int(100, 999),
                        'Answered' => random_int(100, 999),
                        'CPC' => random_int(100, 999),
                        '%CPC' => random_int(1, 99),
                        'CPCA' => random_int(100, 999),
                        '%CPCA' => random_int(1, 99),
                        'Deals' => random_int(100, 999),
                        '%Deals' => random_int(1, 99),
                    ],
                    [
                        'Agent' => random_int(1000, 9999),
                        'Attempts' => random_int(100, 999),
                        'Answered' => random_int(100, 999),
                        'CPC' => random_int(100, 999),
                        '%CPC' => random_int(1, 99),
                        'CPCA' => random_int(100, 999),
                        '%CPCA' => random_int(1, 99),
                        'Deals' => random_int(100, 999),
                        '%Deals' => random_int(1, 99),
                    ],
                    [
                        'Agent' => random_int(1000, 9999),
                        'Attempts' => random_int(100, 999),
                        'Answered' => random_int(100, 999),
                        'CPC' => random_int(100, 999),
                        '%CPC' => random_int(1, 99),
                        'CPCA' => random_int(100, 999),
                        '%CPCA' => random_int(1, 99),
                        'Deals' => random_int(100, 999),
                        '%Deals' => random_int(1, 99),
                    ],
                    [
                        'Agent' => random_int(1000, 9999),
                        'Attempts' => random_int(100, 999),
                        'Answered' => random_int(100, 999),
                        'CPC' => random_int(100, 999),
                        '%CPC' => random_int(1, 99),
                        'CPCA' => random_int(100, 999),
                        '%CPCA' => random_int(1, 99),
                        'Deals' => random_int(100, 999),
                        '%Deals' => random_int(1, 99),
                    ],
                ]
            ],
            'detailsCPC' => [
                [
                    'x' => 100,
                    'y' => 100,
                    'value' => 1000,
                    'company' => 'Flex'
                ],
                [
                    'x' => 90,
                    'y' => 50,
                    'value' => 1200,
                    'company' => 'Paschoalotto'
                ],
                [
                    'x' => 20,
                    'y' => 110,
                    'value' => 800,
                    'company' => 'Syscom'
                ],
                [
                    'x' => 180,
                    'y' => 12,
                    'value' => 550,
                    'company' => 'Zanc'
                ],
            ],
            'detailsDeals' => [
                [
                    'x' => 100,
                    'y' => 100,
                    'value' => 1000,
                    'company' => 'Flex'
                ],
                [
                    'x' => 90,
                    'y' => 50,
                    'value' => 1200,
                    'company' => 'Paschoalotto'
                ],
                [
                    'x' => 20,
                    'y' => 110,
                    'value' => 800,
                    'company' => 'Syscom'
                ],
                [
                    'x' => 180,
                    'y' => 12,
                    'value' => 550,
                    'company' => 'Zanc'
                ],
            ],
            'detailsImproductive' => [
                [
                    'x' => 100,
                    'y' => 100,
                    'value' => 1000,
                    'company' => 'Flex'
                ],
                [
                    'x' => 90,
                    'y' => 50,
                    'value' => 1200,
                    'company' => 'Paschoalotto'
                ],
                [
                    'x' => 20,
                    'y' => 110,
                    'value' => 800,
                    'company' => 'Syscom'
                ],
                [
                    'x' => 180,
                    'y' => 12,
                    'value' => 550,
                    'company' => 'Zanc'
                ],
            ],
            'detailsMute' => [
                [
                    'x' => 100,
                    'y' => 100,
                    'value' => 1000,
                    'company' => 'Flex'
                ],
                [
                    'x' => 90,
                    'y' => 50,
                    'value' => 1200,
                    'company' => 'Paschoalotto'
                ],
                [
                    'x' => 20,
                    'y' => 110,
                    'value' => 800,
                    'company' => 'Syscom'
                ],
                [
                    'x' => 180,
                    'y' => 12,
                    'value' => 550,
                    'company' => 'Zanc'
                ],
            ],
            'detailsMachine' => [
                [
                    'x' => 100,
                    'y' => 100,
                    'value' => 1000,
                    'company' => 'Flex'
                ],
                [
                    'x' => 90,
                    'y' => 50,
                    'value' => 1200,
                    'company' => 'Paschoalotto'
                ],
                [
                    'x' => 20,
                    'y' => 110,
                    'value' => 800,
                    'company' => 'Syscom'
                ],
                [
                    'x' => 180,
                    'y' => 12,
                    'value' => 550,
                    'company' => 'Zanc'
                ],
            ],
        ];


        return response()->json($data);
    }
}
